ubuntu_version: 'ubuntu focal'
ansible_user: 'phoenix'
ansible_password: 'Phoenix1!'
ssh_key_location: '/home/jd/.ssh/id_rsa.pub'

mongodb_user: phoenix
mongodb_admin: phoenix_admin
mongodb_passwd: Phoenix1!
docker_group: docker

mongodb_dir: /mongo_cluster/

# Mongo version
mongodb_docker_image_tag: 4.2.6

mongodb_port: 27017
mongodb_shard1_port: 27018
mongodb_shard2_port: 27019
mongodb_shard3_port: 27020