---
- hosts: server
  become: true
  vars_files:
    -  vars/default.yml

  tasks: 
    - name: Run minio container
      become: true
      docker_container:
        name: minio
        image: minio/minio
        command: server /data
        restart_policy: always
        state: started
        env:
          MINIO_ACCESS_KEY: "12345678" 
          MINIO_SECRET_KEY: "12345678"
        volumes:
          - "/phoenixvault:/data"
        ports:
          - "10.20.0.99:9000:9000"


